DROP TABLE IF EXISTS SUBSCRIBER;

CREATE TABLE SUBSCRIBER (ID LONG PRIMARY KEY AUTO_INCREMENT NOT NULL,
NAME VARCHAR(30),
TOPIC VARCHAR(30)
);

DROP TABLE IF EXISTS MESSAGES;

CREATE TABLE MESSAGES (ID LONG PRIMARY KEY AUTO_INCREMENT NOT NULL,
SUBSCRIBER_ID LONG NOT NULL,
MESSAGE VARCHAR(300),
READ BOOLEAN
);

INSERT INTO SUBSCRIBER (NAME, TOPIC) VALUES ('Karen', 'ANDROID');
INSERT INTO SUBSCRIBER (NAME, TOPIC) VALUES ('Bill', 'IPHONE');

INSERT INTO MESSAGES (SUBSCRIBER_ID, MESSAGE, READ) VALUES (1, 'Our most popular pre-owned phone is now just $3/mo.', false);
INSERT INTO MESSAGES (SUBSCRIBER_ID, MESSAGE, READ) VALUES (1, 'phones with Unlimited Basic for $25/mo. per line for 5 lines!', true);